name: ipyui_sdk
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  fluent_ui: ^4.12.0
  web_socket_channel: ^3.0.3
  macos_ui: ^2.2.0
  cupertino_icons: ^1.0.8
  window_manager: ^0.3.9
  provider: ^6.1.1
  # UI & Assets
  flutter_svg: ^2.0.10
  lottie: ^3.1.0        # Animatsiyalar uchun
  google_fonts: ^6.1.0
  flutter_blurhash: ^0.8.2
  cached_network_image: ^3.3.1 # Rasmlar keshlanishi uchun
  # Native Capabilities
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  vibration: ^1.8.4
  file_picker: ^6.1.1
  geolocator: ^11.0.0   # GPS
  device_info_plus: ^9.1.2
  video_player: ^2.8.6  # Video
  chewie: ^1.8.1        # Video UI
  webview_flutter: ^4.7.0 # Web Browser ichida
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
