name: ipyui_sdk
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  fluent_ui: ^4.0.0
  web_socket_channel: ^3.0.3
  macos_ui: ^2.2.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  google_fonts: ^6.1.0
  http: ^1.1.0
  connectivity_plus: ^5.0.0 # To detect network changes

  flutter_svg: ^2.0.9 # For custom SVG icons/favicons

  # --- Desktop Window Management (Custom Title Bar) ---
  window_manager: ^0.3.8 # Resize, Move, Hide Titlebar
  screen_retriever: ^0.1.9

  # --- Plugins (The 15+ Native Features) ---
  url_launcher: ^6.2.4
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  file_picker: ^6.1.1
  geolocator: ^11.0.0
  vibration: ^1.8.4
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  
  # --- Advanced ---
  device_info_plus: ^9.1.2 # For identifying OS to Python
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
